openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: http://localhost:3610/v1
paths:
  /auth/register:
    post:
      tags:
        - auth
      summary: Register a new user
      description: |
        This endpoint allows users to register in the system by providing an email and password.
        Clients are expected to send a POST request with a JSON body containing the credentials of the new user.
        Upon successful registration, the user will be able to access additional functionalities of the system.
      x-eov-operation-handler: authController
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name associated with the account.
                  example: My personal account
                email:
                  type: string
                  description: The email address associated with the account.
                  example: test@myaccount.com
                password:
                  type: string
                  description: The password for the account.
                  example: MyPassword
              required:
                - email
                - password
              additionalProperties: false
      responses:
        200:
          description: OK
  /auth/login:
    post:
      tags:
        - auth
      summary: Log in with email and password
      description: |
        This endpoint allows users to log in to the system using their registered email and password.
        Clients are expected to send a POST request with a JSON body containing the user's credentials.
        Upon successful authentication, the endpoint returns a JWT (JSON Web Token) which can be used for accessing authorized functionalities.
      x-eov-operation-handler: authController
      operationId: loginWithEmailAndPassword
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: The email address associated with the account.
                  example: test@myaccount.com
                password:
                  type: string
                  description: The password for the account.
                  example: MyPassword
              required:
                - email
                - password
              additionalProperties: false
      responses:
        200:
          description: OK
  /application:
    post:
      tags:
        - application
      summary: Create a new application
      description: |
        This endpoint allows you to create a new application. You need to provide the ID of the account associated with the application, the name of the application, an optional description, the URL or path to the application's logo, and whether the application is enabled or not.
      x-eov-operation-handler: applicationController
      operationId: create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                accountId:
                  type: string
                  description: The ID of the account associated with the application.
                name:
                  type: string
                  description: The name of the application.
                description:
                  type: string
                  description: The description of the application.
                logo:
                  type: string
                  description: The URL or path to the logo of the application.
                enabled:
                  type: boolean
                  description: Indicates whether the application is enabled or not.
                  default: true
              required:
                - accountId
                - name
                - enabled
              additionalProperties: false
      responses:
        200:
          description: OK
